/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : hw_irqs.h
**     Project     : ee4951_prodmcu
**     Processor   : MK22FN512VLL12
**     Component   : Init_GPIO
**     Version     : Component 01.008, Driver 01.08, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-12-01, 12:42, # CodeGen: 14
**     Abstract    :
**          This file implements the GPIO (PTA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : hw_irqs
**          Device                                         : PTA
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Pin 0                                        : Do not initialize
**            Pin 1                                        : Do not initialize
**            Pin 2                                        : Do not initialize
**            Pin 3                                        : Do not initialize
**            Pin 4                                        : Do not initialize
**            Pin 5                                        : Initialize
**              Pin direction                              : Input
**              Output value                               : 0
**              Open drain                                 : <Automatic>
**              Pull resistor                              : <Automatic>
**              Pull selection                             : <Automatic>
**              Slew rate                                  : <Automatic>
**              Drive strength                             : <Automatic>
**              Interrupt/DMA request                      : Interrupt on rising
**              Passive filter                             : <Automatic>
**              Lock                                       : <Automatic>
**            Pin 12                                       : Do not initialize
**            Pin 13                                       : Initialize
**              Pin direction                              : Input
**              Output value                               : 0
**              Open drain                                 : <Automatic>
**              Pull resistor                              : <Automatic>
**              Pull selection                             : Pull Up
**              Slew rate                                  : <Automatic>
**              Drive strength                             : <Automatic>
**              Interrupt/DMA request                      : DMA on falling
**              Passive filter                             : Disabled
**              Lock                                       : <Automatic>
**            Pin 14                                       : Do not initialize
**            Pin 15                                       : Do not initialize
**            Pin 16                                       : Do not initialize
**            Pin 17                                       : Do not initialize
**            Pin 18                                       : Do not initialize
**            Pin 19                                       : Do not initialize
**          Pin selection/routing                          : 
**            Pin 0                                        : Disabled
**            Pin 1                                        : Disabled
**            Pin 2                                        : Disabled
**            Pin 3                                        : Disabled
**            Pin 4                                        : Disabled
**            Pin 5                                        : Enabled
**              Pin                                        : PTA5/USB_CLKIN/FTM0_CH2/I2S0_TX_BCLK/JTAG_TRST_b
**            Pin 12                                       : Disabled
**            Pin 13                                       : Enabled
**              Pin                                        : PTA13/LLWU_P4/FTM1_CH1/I2S0_TX_FS/FTM1_QD_PHB
**            Pin 14                                       : Disabled
**            Pin 15                                       : Disabled
**            Pin 16                                       : Disabled
**            Pin 17                                       : Disabled
**            Pin 18                                       : Disabled
**            Pin 19                                       : Disabled
**          Interrupts                                     : 
**            Port interrupt                               : Enabled
**              Interrupt                                  : INT_PORTA
**              Interrupt request                          : Enabled
**              Interrupt priority                         : 0
**              ISR Name                                   : PORTA_IRQHandler
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void hw_irqs_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file hw_irqs.h
** @version 01.08
** @brief
**          This file implements the GPIO (PTA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup hw_irqs_module hw_irqs module documentation
**  @{
*/         

#ifndef hw_irqs_H_
#define hw_irqs_H_

/* MODULE hw_irqs. */

#include "PTA_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define hw_irqs_Init PTA_Init
/* PDD macros peripheral base address parameter */
#define hw_irqs_DEVICE PTA_BASE_PTR
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see hw_irqs.c file for more information).
** ===================================================================
*/
PE_ISR(PORTA_IRQHandler);

#ifdef __cplusplus
}
#endif

/* END hw_irqs. */
#endif /* #ifndef __hw_irqs_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/


