/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : ee4951_prod_mcu
**     Processor   : MK22FN512VLL12
**     Component   : MK22FN512LL12_4SDK
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Datasheet   : K22P121M120SF7RM, Rev. 1, March 24, 2014
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-11-26, 12:20, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemInit            - void SystemInit(void);
**         SystemCoreClockUpdate - void SystemCoreClockUpdate(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Cpu.h"
#include "Events.h"


#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  Common_Init (component MK22FN512LL12_4SDK)
**     Description :
**         Initialization of registers for that there is no 
**         initialization component.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMMON_INIT
void Common_Init(void)
{
  /* This function contains initialization code which is not part of initialization 
     methods of peripheral initialization (Init) components used in the project.  
     This function is generated depending on Init components present 
     in the project. To remove initialization of a register from the Common_Init() 
     add Init component that includes initialization of this register.
     This function is also affected by after reset value optimization property 
     available in Component view\Generator_Configurations\Active configuration\
     Optimizations\Utilize after reset values. */
  /* Enable clock gate of peripherals initialized in Common_Init() */
  /* SIM_SCGC5: PORTA=1 */
  SIM_SCGC5 |= SIM_SCGC5_PORTA_MASK;

  /* SIM_SCGC5: PORTA=1 */
  SIM_SCGC5 |= SIM_SCGC5_PORTA_MASK;
  /* NVICIP59: PRI59=0 */
  NVICIP59 = NVIC_IP_PRI59(0x00);
  /* NVICISER1: SETENA|=0x08000000 */
  NVICISER1 |= NVIC_ISER_SETENA(0x08000000);
  /* PORTA_PCR5: ISF=0,IRQC=0x0A,LK=0,DSE=0,PFE=0,PE=1 */
  PORTA_PCR5 = (uint32_t)((PORTA_PCR5 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_IRQC(0x05) |
                PORT_PCR_LK_MASK |
                PORT_PCR_DSE_MASK |
                PORT_PCR_PFE_MASK
               )) | (uint32_t)(
                PORT_PCR_IRQC(0x0A) |
                PORT_PCR_PE_MASK
               ));

  /* Disable clock gate of peripherals initialized in Common_Init() */
}

#endif /* CPU_COMMON_INIT */
/*
** ===================================================================
**     Method      :  Components_Init (component MK22FN512LL12_4SDK)
**     Description :
**         Initialization of components (with exception for Peripheral
**         Initialization Components which are initialized in 
**         Peripherals_Init() method).
**         For example, if automatic initialization feature 
**         is enabled in LDD component then its Init method call 
**         is executed in Components_Init() method.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMPONENTS_INIT
void Components_Init(void)
{

  /*! debug_console Auto initialization start */
  /* Debug console initialization */
  DbgConsole_Init(BOARD_DEBUG_UART_INSTANCE, DEBUG_UART_BAUD, DEBUG_UART_TYPE);
  /*! debug_console Auto initialization end */
  /*! dut_range_gpio Auto initialization start */
  GPIO_DRV_Init(NULL,dut_range_gpio_OutConfig0);
  /*! dut_range_gpio Auto initialization end */
  
  /*! dut_adc Auto initialization start */
  ADC16_DRV_Init(FSL_DUT_ADC, &dut_adc_InitConfig0);
  ADC16_DRV_ConfigConvChn(FSL_DUT_ADC, 0U, &dut_vsense_config);
  /*! dut_adc Auto initialization end */
  
  /*! self_adc Auto initialization start */
  ADC16_DRV_Init(FSL_SELF_ADC, &self_adc_InitConfig0);
  ADC16_DRV_ConfigConvChn(FSL_SELF_ADC, 0U, &self3v3_vsense_config);
  /*! self_adc Auto initialization end */
  
  /*! disp_gpio Auto initialization start */
  GPIO_DRV_Init(NULL,disp_gpio_OutConfig0);
  /*! disp_gpio Auto initialization end */
  
  /*! disp_spi Auto initialization start */
  DSPI_DRV_MasterInit(FSL_DISP_SPI, &disp_spi_MasterState, &disp_spi_MasterConfig0);
  DSPI_DRV_MasterConfigureBus(FSL_DISP_SPI, &disp_spi_BusConfig0, &disp_spi_calculatedBaudRate);
  /*! disp_spi Auto initialization end */
  
  /*! sd_gpio Auto initialization start */
  GPIO_DRV_Init(sd_gpio_InpConfig0,NULL);
  /*! sd_gpio Auto initialization end */
  
  /*! fsl_dspi1 Auto initialization start */
  DSPI_DRV_MasterInit(FSL_FSL_DSPI1, &fsl_dspi1_MasterState, &fsl_dspi1_MasterConfig0);
  DSPI_DRV_MasterConfigureBus(FSL_FSL_DSPI1, &fsl_dspi1_BusConfig0, &fsl_dspi1_calculatedBaudRate);
  /*! fsl_dspi1 Auto initialization end */
  
  /*! sd_card Auto initialization start */
  sd_card_spi_state.busBaudRate = fsl_dspi1_calculatedBaudRate;
  (void)SDSPI_DRV_Init(&sd_card_spi_state,&sd_card_state);
  /*! sd_card Auto initialization start */

}
#endif /* CPU_COMPONENTS_INIT */


#ifdef __cplusplus
}
#endif

/* END Cpu. */

