/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : memoryCard1.h
**     Project     : sd_w_fatfs
**     Processor   : MK22FN512VLL12
**     Component   : fsl_sdcard
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-12-13, 17:54, # CodeGen: 1
**     Contents    :
**         SDSPI_DRV_Init           - sdspi_status_t SDSPI_DRV_Init(sdspi_spi_t * spi,sdspi_card_t * card);
**         SDSPI_DRV_ReadBlocks     - sdspi_status_t SDSPI_DRV_ReadBlocks(sdspi_spi_t * spi,sdspi_card_t *...
**         SDSPI_DRV_WriteBlocks    - sdspi_status_t SDSPI_DRV_WriteBlocks(sdspi_spi_t * spi,sdspi_card_t *...
**         SDSPI_DRV_CheckReadOnly  - bool SDSPI_DRV_CheckReadOnly(sdspi_spi_t * spi,sdspi_card_t * card);
**         SDSPI_DRV_Shutdown       - void SDSPI_DRV_Shutdown(sdspi_spi_t * spi,sdspi_card_t * card);
**         SDCARD_DRV_Init          - sdhc_status_t SDCARD_DRV_Init(sdhc_host_t * host,sdhc_card_t * card);
**         SDCARD_DRV_ReadBlocks    - sdhc_status_t SDCARD_DRV_ReadBlocks(sdhc_card_t * card,uint8_t *...
**         SDCARD_DRV_WriteBlocks   - sdhc_status_t SDCARD_DRV_WriteBlocks(sdhc_card_t * card,uint8_t *...
**         SDCARD_DRV_EraseBlocks   - sdhc_status_t SDCARD_DRV_EraseBlocks(sdhc_card_t * card,uint32_t...
**         SDCARD_DRV_CheckReadOnly - bool SDCARD_DRV_CheckReadOnly(sdhc_card_t * card);
**         SDCARD_DRV_Shutdown      - void SDCARD_DRV_Shutdown(sdhc_card_t * card);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file memoryCard1.h
** @version 01.00
*/         
/*!
**  @addtogroup memoryCard1_module memoryCard1 module documentation
**  @{
*/         
#ifndef __memoryCard1_H
#define __memoryCard1_H
/* MODULE memoryCard1. */
/* Include inherited beans */
#include "osa1.h"
#include "fsl_dspi1.h"
#include "Cpu.h"
#include "fsl_sdmmc_card.h"
/*! memoryCard1 state structure using DSPI */  
extern sdspi_card_t memoryCard1_state;
    
/*! SPIx/DSPI device state structure */  
extern sdspi_spi_t memoryCard1_spi_state;
    
/*! Structure containing pointers to API layer between SDCARD and SPI/DSPI components */  
extern sdspi_ops_t ops_layer;
#endif
/* ifndef __memoryCard1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
